### ISSUE TITLE
Missing reportlab for python3 

### ISSUE THREAD

**Issue by simbulu** [trndr/byti#2]
Running byti.py with python3:

```
$ head byti.py
#!/usr/bin/env python3
from tkinter import *
import tkinter.font
import numpy, os, sys
from datetime import date
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
```

The result is this

```
$ ./byti.py
Traceback (most recent call last):
  File "./byti.py", line 6, in <module>
    from reportlab.pdfgen import canvas
ImportError: No module named 'reportlab'
```

This indicates we are are missing some python dependency called something like 'reportlab`
Now what is available from our standard repositories?

```
$ yum list | grep reportlab
python-reportlab.x86_64                  2.5-9.el7                    @base     
python-reportlab-docs.x86_64             2.5-9.el7                    @base     
```

Meaning, there is no python3 module for reportlab available.

python3 seems to refuse to use the installed version of python-reportlab (v. 2.5).

Do you have any hints on how we can install python-reportlab v.3 on a rpm system (CentOS 7) ?

**Comment by trndr** [comment]
reportlab dependency has been removed
